build_wheel:
  stage: build
  image: python:3.7
  script:
    # Install dependencies
    - python3 -m pip install --user --upgrade virtualenv setuptools wheel
    # Install OctoPrint
    - pushd ..
    - git clone https://github.com/foosel/OctoPrint
    - pushd OctoPrint
    - python3 -m virtualenv venv
    - source venv/bin/activate
    - python3 -m pip install -e .[develop,plugins]
    - popd ; popd
    # Build plugin
    - python3 setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist/

dist_wheel:
  stage: deploy
  image: python:3
  script:
    - python3 -m pip install --user --upgrade twine
    - python3 -m twine upload -u __token__ dist/*
